### ISSUE TITLE
Insert links to favorite and archive the content

### ISSUE THREAD

**Issue by gilsondev** [emiraydin/p2k#10]
It would be interesting to do the same readability, which in each content, put two links:
- Favorite this article;
- Archive this article.

Thus, the kindle itself, would be able to label and archive any item you want to search in the future.

**Comment by emiraydin** [comment]
@gilsondev I think the app would have to navigate away to a web page to do that, which would interfere with the overall experience and release info through a GET request which is not secure (would need to generate security code per each article to make it work but that would be very cumbersome). Since it's not possible to access any Kindle internal software to send a REST HTTP request and the document sent by P2K is a static document, I'm marking this as wontfix. If you know any other way, let me know and I'll consider it. Thanks!

**Comment by gilsondev** [comment]
I suggested this because the readability offers these links.
